-- Temporary fixtures only. A successful run always rolls back all identities and games.
begin;
create temporary table contest_test_users(label text primary key,id uuid not null) on commit drop;
insert into contest_test_users values ('host',gen_random_uuid()),('guest',gen_random_uuid()),('outsider',gen_random_uuid());
insert into auth.users(id,aud,role,email,email_confirmed_at,raw_user_meta_data,created_at,updated_at)
select id,'authenticated','authenticated',id::text||'@contest-test.invalid',now(),jsonb_build_object('name','Fixture '||label),now(),now()
from contest_test_users;
grant select on contest_test_users to authenticated;

-- Byte-for-byte seed fixtures generated by the same algorithm used by Kotlin.
do $$ begin
  assert contest_internal.initial_board(1)=array[2,1,7,3,0,5,6,8,4], 'seed1 mismatch';
  assert contest_internal.initial_board(42)=array[0,4,8,1,2,3,6,5,7], 'seed42 mismatch';
  assert contest_internal.initial_board(1234)=array[4,8,0,6,5,1,7,2,3], 'seed1234 mismatch';
  assert contest_internal.initial_board(2147483646)=array[2,4,5,6,3,1,0,7,8], 'max seed mismatch';
end $$;

set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',id,'role','authenticated')::text,true)
from contest_test_users where label='host';
select public.contest_ensure_profile();
do $$ declare row_data jsonb; blocked boolean:=false; begin
  row_data:=public.contest_update_profile('Host Updated','Moscow',null);
  assert (row_data->>'id')::uuid=auth.uid() and row_data->>'name'='Host Updated','profile RPC did not use current actor';
  begin perform public.contest_update_profile('X','Moscow',null); exception when others then blocked:=true; end;
  assert blocked,'profile RPC accepted invalid name';
end $$;
select set_config('contest.test_game',public.contest_create_game('Smoke Circle','CIRCLE',now(),now()+interval '1 hour',100,'Rollback-only test')->>'id',true);
select set_config('contest.test_image',public.contest_create_game('Smoke Image','IMAGE',now(),now()+interval '1 hour',100,'Rollback-only test')->>'id',true);
select set_config('contest.test_solved_image',public.contest_create_game('Smoke Solved Image','IMAGE',now(),now()+interval '1 hour',100,'Rollback-only test')->>'id',true);
select set_config('contest.test_forfeit',public.contest_create_game('Smoke Forfeit','CIRCLE',now(),now()+interval '1 hour',50,'Rollback-only test')->>'id',true);
select set_config('contest.test_future',public.contest_create_game('Smoke Future','CIRCLE',now()+interval '1 hour',now()+interval '2 hours',100,'Rollback-only test')->>'id',true);

-- A game cannot start without an opponent. A client cannot overwrite server-owned points.
do $$ declare blocked boolean:=false; begin
  begin perform public.contest_start_game(current_setting('contest.test_game')::uuid); exception when others then blocked:=true; end;
  assert blocked, 'started without opponent';
  blocked:=false;
  begin update public.contest_profiles set points=999999 where id=auth.uid(); exception when insufficient_privilege then blocked:=true; end;
  assert blocked, 'client modified points';
end $$;

select set_config('request.jwt.claims',jsonb_build_object('sub',id,'role','authenticated')::text,true)
from contest_test_users where label='guest';
select public.contest_ensure_profile();
select public.contest_join_game(current_setting('contest.test_game')::uuid);
select public.contest_join_game(current_setting('contest.test_image')::uuid);
select public.contest_join_game(current_setting('contest.test_solved_image')::uuid);
select public.contest_join_game(current_setting('contest.test_forfeit')::uuid);
select public.contest_join_game(current_setting('contest.test_future')::uuid);
do $$ declare blocked boolean:=false; begin
  begin perform public.contest_start_game(current_setting('contest.test_future')::uuid); exception when others then blocked:=true; end;
  assert blocked, 'future match started early';
  blocked:=false;
  begin perform public.contest_forfeit_game(current_setting('contest.test_future')::uuid); exception when others then blocked:=true; end;
  assert blocked,'scheduled forfeit awarded an early victory';
end $$;

-- A third player cannot join, submit, forfeit, modify a profile, or write a game directly.
select set_config('request.jwt.claims',jsonb_build_object('sub',id,'role','authenticated')::text,true)
from contest_test_users where label='outsider';
select public.contest_ensure_profile();
do $$ declare blocked boolean; changed integer; begin
  blocked:=false;
  begin perform public.contest_join_game(current_setting('contest.test_game')::uuid); exception when others then blocked:=true; end;
  assert blocked, 'third player joined';
  blocked:=false;
  begin perform public.contest_save_result(current_setting('contest.test_game')::uuid,array[5,4,3,2,1]); exception when others then blocked:=true; end;
  assert blocked, 'outsider submitted result';
  blocked:=false;
  begin perform public.contest_forfeit_game(current_setting('contest.test_game')::uuid); exception when others then blocked:=true; end;
  assert blocked, 'outsider forfeited another game';
  update public.contest_profiles set name='Wrong user' where id=(select id from contest_test_users where label='host');
  get diagnostics changed = row_count;
  assert changed=0, 'RLS permitted editing another profile';
  blocked:=false;
  begin update public.contest_games set winner_id=auth.uid() where id=current_setting('contest.test_game')::uuid; exception when insufficient_privilege then blocked:=true; end;
  assert blocked, 'direct game modification permitted';
  assert (select count(*) from public.contest_participants)=0, 'outsider read private participation';
end $$;

reset role;
update public.contest_games set image_seed=42 where id=current_setting('contest.test_solved_image')::uuid;
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',id,'role','authenticated')::text,true)
from contest_test_users where label='host';
select public.contest_start_game(current_setting('contest.test_game')::uuid);
select public.contest_start_game(current_setting('contest.test_image')::uuid);
do $$ declare blocked boolean; g jsonb; after_points integer; begin
  blocked:=false;
  begin perform public.contest_save_result(current_setting('contest.test_game')::uuid,array[5,4,null,2,1]); exception when others then blocked:=true; end;
  assert blocked, 'null circle move accepted';
  blocked:=false;
  begin perform public.contest_save_result(current_setting('contest.test_game')::uuid,array[1,2,3,4,5]); exception when others then blocked:=true; end;
  assert blocked, 'ascending circles accepted';
  blocked:=false;
  begin perform public.contest_save_result(current_setting('contest.test_image')::uuid,array[-1]); exception when others then blocked:=true; end;
  assert blocked, 'invalid image move accepted';
  g:=public.contest_save_result(current_setting('contest.test_game')::uuid,array[5,4,3,2,1]);
  assert g->>'status'='FINISHED' and (g->>'winner_id')::uuid=auth.uid(), 'valid Circle winner not recorded';
  g:=public.contest_save_result(current_setting('contest.test_game')::uuid,array[5,4,3,2,1]);
  select points into after_points from public.contest_profiles where id=auth.uid();
  assert after_points=100, 'repeat result awarded twice';
  assert (public.contest_statistics()->>'circle_wins')::integer=1, 'statistics missing victory';
  assert (public.contest_statistics()->>'weekly_points')::integer=100, 'weekly points incorrect';
  perform public.contest_start_game(current_setting('contest.test_solved_image')::uuid);
  -- A* solution for seed 42; independent from the scramble generator.
  g:=public.contest_save_result(current_setting('contest.test_solved_image')::uuid,array[1,4,3,6,7,8,5,2,1,4,3,6,7,4,5,8,7,4,3,0,1,2,5,8]);
  assert g->>'status'='FINISHED' and (g->>'winner_id')::uuid=auth.uid(),'valid Image replay was not accepted';
  assert (public.contest_statistics()->>'image_wins')::integer=1,'Image win missing from statistics';
end $$;

select set_config('request.jwt.claims',jsonb_build_object('sub',id,'role','authenticated')::text,true)
from contest_test_users where label='guest';
do $$ declare g jsonb; begin
  g:=public.contest_save_result(current_setting('contest.test_game')::uuid,array[5,4,3,2,1]);
  assert (g->>'winner_id')::uuid=(select id from contest_test_users where label='host'), 'late submit changed winner';
  perform public.contest_start_game(current_setting('contest.test_forfeit')::uuid);
  g:=public.contest_forfeit_game(current_setting('contest.test_forfeit')::uuid);
  assert (g->>'winner_id')::uuid=(select id from contest_test_users where label='host'), 'forfeit did not award opponent';
end $$;

-- Simulate a disappeared participant without waiting 45 real seconds.
reset role;
update public.contest_participants set last_seen_at=now()-interval '46 seconds'
 where game_id=current_setting('contest.test_image')::uuid and user_id=(select id from contest_test_users where label='guest');
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',id,'role','authenticated')::text,true)
from contest_test_users where label='guest';
do $$ declare g jsonb; begin
  g:=public.contest_get_game(current_setting('contest.test_image')::uuid);
  assert (g->>'winner_id')::uuid=(select id from contest_test_users where label='host'), 'stale caller revived heartbeat';
end $$;

reset role;
set local role anon;
do $$ declare blocked boolean:=false; begin
  begin perform public.contest_statistics(); exception when insufficient_privilege then blocked:=true; end;
  assert blocked, 'anonymous RPC allowed';
end $$;
reset role;
select 'PASS: seed parity; profile RPC; slot ownership; RLS; start; Image and Circle replay validation; winner idempotence; statistics; forfeit; heartbeat; anon denial' as smoke_test;
rollback;
